nome_1 = (input('Digite o nome da primeira pessoa: '))
nome_2 = (input('Digite o nome da segunda pessoa: '))
nome_3 = (input('Digite o nome da terceira pessoa: '))
peso_1 = float(input('Digite o peso da primeira pessoa' ))
peso_2 = float(input('Digite o peso da segunda pessoa' ))
peso_3 = float(input('Digite o peso da terceira pessoa' ))
altura_1 = float(input('Digite a altura da primeira pessoa: '))
altura_2 = float(input('Digite a altura da segunda pessoa: '))
altura_3 = float(input('Digite a altura da terceira pessoa: '))
print('O IMC de ', nome_1, 'é: ', (peso_1 / (altura_1 * altura_1)))
print('O IMC de ', nome_2, 'é: ', (peso_2 / (altura_2 * altura_2)))
print(f'O IMC de {nome_3} e {peso_3 / (altura_3 * altura_3):.2f}')
